services:
  bot:
    build: .
    container_name: jarqyndos-bot
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_HOST: db
      POSTGRES_DB: peer2peer
      ENVIRONMENT: production

  db:
    image: postgres:15
    container_name: jarqyndos-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgresuser
      POSTGRES_DB: peer2peer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresuser -d peer2peer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
