services:
  bot:
    build: .
    container_name: telegram-bot
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_USER: octoberskyler
      MYSQL_PASSWORD: kimep
      MYSQL_HOST: db
      MYSQL_DATABASE: peer2peer

  db:
    image: mysql:9.2
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kimep
      MYSQL_USER: octoberskyler
      MYSQL_PASSWORD: kimep
      MYSQL_DATABASE: peer2peer
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: octoberskyler
      PMA_PASSWORD: kimep
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  mysql_data:
