version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: octoberskyler
      POSTGRES_PASSWORD: kimep
      POSTGRES_HOST: db
      POSTGRES_DATABASE: peer2peer
      ENV: PROD

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: octoberskyler
      POSTGRES_PASSWORD: kimep
      POSTGRES_DB: peer2peer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U octoberskyler -d peer2peer"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@artchsh.kz
      PGADMIN_DEFAULT_PASSWORD: kimep
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
